name: wine-quality
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - scikit-learn=1.3.2    # Versi yang tersedia di conda-forge
  - pandas=2.1.4          # Versi yang tersedia
  - numpy=1.26.4          # Versi yang tersedia  
  - matplotlib=3.8.4      # Versi yang tersedia
  - seaborn=0.13.2        # Versi yang tersedia
  - pip:
    - mlflow==2.19.0